---
apiVersion: v1
kind: Service
metadata:
  # dify-api would confict with dify-api program
  # use another name
  name: {{ include "dify.fullname" . }}-api-svc
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-frontend
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-sandbox
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
spec:
  type: {{ .Values.sandbox.service.type }}
  ports:
    - port: {{ .Values.sandbox.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
