{{- if .Values.envs.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.envs.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end -}}
{{- end}}
