{{- if .Values.irc.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "channels.fullname" . }}-irc
  labels:
    app.kubernetes.io/name: {{ include "channels.name" . }}-irc
    app.kubernetes.io/instance: {{ .Release.Name }}-irc
    helm.sh/chart: {{ include "channels.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "channels.name" . }}
spec:
  replicas: {{ .Values.irc.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "channels.name" . }}-irc
      app.kubernetes.io/instance: {{ .Release.Name }}-irc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "channels.name" . }}-irc
        app.kubernetes.io/instance: {{ .Release.Name }}-irc
        app.kubernetes.io/part-of: {{ include "channels.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "channels.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-irc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - irc
          ports:
            - name: irc
              containerPort: {{ .Values.irc.port }}
              protocol: TCP
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.irc.resources | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

# vi: ft=goyaml
