{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "channels.serviceAccountName" . }}
  labels:
{{ include "channels.labels" . | nindent 4 }}
{{- end -}}
