apiVersion: v2
name: codecov
description: A Helm chart for Kubernetes

home: https://github.com/codecov/self-hosted

maintainers:
  - name: douban

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "24.4.1"

dependencies:
  - name: redis
    version: ~17.15.6
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: redis.embedded
  - name: postgresql
    version: ~12.8.5
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.embedded
  - name: timescaledb-single
    alias: timescaledb
    version: 0.33.*
    repository: https://charts.timescale.com/
    condition: timescaledb.enabled
  - name: minio
    version: ~12.7.0
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: minio.embedded
