apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cbs-csi-controller.serviceAccountName" . }}
  labels:
    {{- include "cbs-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}