kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cbs-csi-node.clusterRoleBindingName" . }}
  labels:
    {{- include "cbs-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleBinding.node.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cbs-csi-node.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cbs-csi-node.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io