{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbs-csi-driver.secretName" . }}
  labels:
    {{- include "cbs-csi-driver.labels" . | nindent 4 }}
type: Opaque
data:
  TENCENTCLOUD_CBS_API_SECRET_ID: {{ required "secret.secretId is required" .Values.secret.secretId | b64enc }}
  TENCENTCLOUD_CBS_API_SECRET_KEY: {{ required "secret.secretKey is required" .Values.secret.secretKey | b64enc }}
{{- else }}
  {{- if not .Values.secret.existingSecret }}
    {{- required "When secret.create is false, you must specify an existingSecret" nil }}
  {{- end }}
{{- /* Just referencing existing secret */}}
{{- end }}