{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbs-csi-driver.secretName" . }}
  labels:
    {{- include "cbs-csi-driver.labels" . | nindent 4 }}
type: Opaque
data:
  TENCENTCLOUD_CBS_API_SECRET_ID: {{ .Values.secret.secretId | b64enc }}
  TENCENTCLOUD_CBS_API_SECRET_KEY: {{ .Values.secret.secretKey | b64enc }}
{{- end }}