apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overlord.fullname" . }}-apiserver
  labels:
    app.kubernetes.io/name: {{ include "overlord.name" . }}
    app.kubernetes.io/instance: apiserver
    helm.sh/chart: {{ include "overlord.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "overlord.name" . }}
      app.kubernetes.io/instance: apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "overlord.name" . }}
        app.kubernetes.io/instance: apiserver
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - apiserver
            - -std
            - -conf
            - /app/config/apiserver.toml
          volumeMounts:
            - name: config
              mountPath: /app/config/
              readOnly: true
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.secretName }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overlord.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "overlord.name" . }}
    app.kubernetes.io/instance: scheduler
    helm.sh/chart: {{ include "overlord.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "overlord.name" . }}
      app.kubernetes.io/instance: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "overlord.name" . }}
        app.kubernetes.io/instance: scheduler
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - scheduler
            - -std
            - -conf
            - /app/config/scheduler.toml
          volumeMounts:
            - name: config
              mountPath: /app/config/
              readOnly: true
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.secretName }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overlord.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "overlord.name" . }}
    app.kubernetes.io/instance: web
    helm.sh/chart: {{ include "overlord.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "overlord.name" . }}
      app.kubernetes.io/instance: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "overlord.name" . }}
        app.kubernetes.io/instance: web
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

# vi: ft=goyaml
