{{- if .Values.vaultStaticSecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "arnor.fullname" . }}
  labels:
    {{- include "arnor.labels" . | nindent 4 }}
spec:
  path: {{ .Values.vaultStaticSecret.path }}
  type: {{ .Values.vaultStaticSecret.type }}
  mount: {{ .Values.vaultStaticSecret.mount }}
  destination:
    create: true
    name: {{ include "arnor.vaultStaticSecretDestination" .}}
    type: "Opaque"
{{- end}}
